title: Session 1: KS1 Storytelling Training - Introduction
hero_image: images/banner.png
description: Session 1 of the online training introduces teachers to the intervention and some of the resources for KS1 Storytelling GBICi1b trial
version: 4
listed: false
copyedit: false
last_tested: "2020-08-19"
steps:
  - title: Introduction to the course
  - title: The Gender Balance in Computing (GBIC) Project
  - title: The Teaching Approach trial
  - title: The Storytelling approach
  - title: Why would storytelling be good for girls?
  - title: Data collection using the online survey
  - title: Additional information and guidance
  - title: Summary of Session 1
